language: python
env:
  - DJANGO="Django>=1.8,<1.9"
  - DJANGO="Django>=1.9,<1.10"
  - DJANGO="Django>=1.10,<1.11"
  - DJANGO="Django>=1.11,<1.12"
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install --upgrade pip setuptools
  - pip install $DJANGO
  - pip install .
notifications:
  irc: "irc.freenode.org#mezzanine"
  on_success: change
  on_failure: change
