language: python
env:
  - DJANGO="Django>=1.7.0,<1.8.0"
  - DJANGO="Django>=1.8.0,<1.9.0"
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
matrix:
  exclude:
    - python: "3.5"
      env: DJANGO="Django>=1.7.0,<1.8.0"
install:
  - pip install $DJANGO
  - pip install .
script:
  - python setup.py test
notifications:
  irc: "irc.freenode.org#mezzanine"
  on_success: change
  on_failure: change
